# Generated by Django 4.0.4 on 2022-07-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
